/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SalesInvoiceGeneratorDesign;

import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import SalesInvoiceGeneratorModel.Invoice_Header;
import SalesInvoiceGeneratorModel.Invoice_Header_Table;
import SalesInvoiceGeneratorModel.Invoice_Line;
import SalesInvoiceGeneratorModel.Invoice_Line_Table;
import java.awt.event.ActionEvent;
import SIG.controller.Action_Listener_Buttons;
import SIG.controller.Action_Listener_Menu_Items;
import SIG.controller.Select_Listener_For_Table;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author FuTuRe
 */
public class SIG_Frame extends javax.swing.JFrame  {
    /**
     * Creates new form SIG_Frame
     */
    public SIG_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Invoice = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_Items = new javax.swing.JTable();
        jButton_Create = new javax.swing.JButton();
        jButton_Create.addActionListener(listenerBtns);
        jButton_Delete = new javax.swing.JButton();
        jButton_Delete.addActionListener(listenerBtns);
        jButton_Save = new javax.swing.JButton();
        jButton_Save.addActionListener(listenerBtns);
        jButton_Cancle = new javax.swing.JButton();
        jButton_Cancle.addActionListener(listenerBtns);
        jLabel_InNumber = new javax.swing.JLabel();
        jLabel_InDate = new javax.swing.JLabel();
        jLabel_CustomerName = new javax.swing.JLabel();
        jLabel_InTotal = new javax.swing.JLabel();
        jTextField_InvoiceDate = new javax.swing.JTextField();
        jTextField_CustomerName = new javax.swing.JTextField();
        jLabel_InvoiceNumber = new javax.swing.JLabel();
        jLabel_InvoiceTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuIteamLoadFile = new javax.swing.JMenuItem();
        jMenuItemSavveFile = new javax.swing.JMenuItem();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Invoice.getSelectionModel().addListSelectionListener(selectListenerForTable);
        jScrollPane1.setViewportView(jTable_Invoice);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 43, 350, 390));

        jTable_Items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable_Items);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 350, 250));

        jButton_Create.setText("Create Invoice");
        jButton_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jButton_Delete.setText("Delete Invoice");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        jButton_Save.setText("Add Item");
        getContentPane().add(jButton_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        jButton_Cancle.setText("Delete Item");
        getContentPane().add(jButton_Cancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        jLabel_InNumber.setText("Inv. No.        :");
        getContentPane().add(jLabel_InNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 88, -1));

        jLabel_InDate.setText("Date              :");
        getContentPane().add(jLabel_InDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 88, -1));

        jLabel_CustomerName.setText("Cust. Name   :");
        getContentPane().add(jLabel_CustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 88, -1));

        jLabel_InTotal.setText("Invoice Total :");
        getContentPane().add(jLabel_InTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 110, -1));
        getContentPane().add(jTextField_InvoiceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 190, -1));
        getContentPane().add(jTextField_CustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 190, -1));
        getContentPane().add(jLabel_InvoiceNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 48, -1));
        getContentPane().add(jLabel_InvoiceTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 44, -1));

        jLabel1.setText("Table of Invoices");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 94, 32));

        jLabel2.setText("INVs Items    :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 94, 32));

        jMenu1.setText("File");

        jMenuIteamLoadFile.setText("Load File");
        jMenuIteamLoadFile.addActionListener(listenerMenuItems);
        jMenu1.add(jMenuIteamLoadFile);

        jMenuItemSavveFile.setText("Save File");
        jMenuItemSavveFile.addActionListener(listenerMenuItems);
        jMenuItemSavveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSavveFileActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSavveFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CreateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jMenuItemSavveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSavveFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSavveFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIG_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIG_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancle;
    private javax.swing.JButton jButton_Create;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_CustomerName;
    private javax.swing.JLabel jLabel_InDate;
    private javax.swing.JLabel jLabel_InNumber;
    private javax.swing.JLabel jLabel_InTotal;
    private javax.swing.JLabel jLabel_InvoiceNumber;
    private javax.swing.JLabel jLabel_InvoiceTotal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIteamLoadFile;
    private javax.swing.JMenuItem jMenuItemSavveFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable_Invoice;
    private javax.swing.JTable jTable_Items;
    private javax.swing.JTextField jTextField_CustomerName;
    private javax.swing.JTextField jTextField_InvoiceDate;
    // End of variables declaration//GEN-END:variables

    private   Action_Listener_Buttons listenerBtns= new Action_Listener_Buttons(this);
    private  Action_Listener_Menu_Items listenerMenuItems=new Action_Listener_Menu_Items(this);
    private ArrayList<Invoice_Header> invoicesArr;
    private Invoice_Header_Table headerTable;
    public static SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
    private Select_Listener_For_Table selectListenerForTable=new Select_Listener_For_Table(this);
    private ArrayList<Invoice_Line> linesArr;
    private Invoice_Line_Table lineTable;

    public Invoice_Line_Table getLineTable() {
        return lineTable;
    }

    public void setLineTable(Invoice_Line_Table lineTable) {
        this.lineTable = lineTable;
    }

    public ArrayList<Invoice_Line> getLinesArr() {
        return linesArr;
    }

    public void setLinesArr(ArrayList<Invoice_Line> linesArr) {
        this.linesArr = linesArr;
    }

    public void setInvoicesArr(ArrayList<Invoice_Header> invoicesArr) {
        this.invoicesArr = invoicesArr;
    }

    public ArrayList<Invoice_Header> getInvoicesArr() {
        return invoicesArr;
    }
    
    public Invoice_Header getInvoiceHeaderObject(int code){
        for(Invoice_Header InvoiceHeaderObject : invoicesArr){
            if(InvoiceHeaderObject.getNumber()==code){
                return InvoiceHeaderObject;
            }
        }
        return null;  //almost non return
    }
    

    public Invoice_Header_Table getHeaderTable() {
        return headerTable;
    }

    public void setHeaderTable(Invoice_Header_Table headerTable) {
        this.headerTable = headerTable;
    }

    public JTable getjTable_Invoice() {
        return jTable_Invoice;
        
    }

    public JTable getjTable_Items() {
        return jTable_Items;
    }

    public JTextField getjTextField_CustomerName() {
        return jTextField_CustomerName;
    }

    public JTextField getjTextField_InvoiceDate() {
        return jTextField_InvoiceDate;
    }

    public JLabel getjLabel_InvoiceNumber() {
        return jLabel_InvoiceNumber;
    }

    public JLabel getjLabel_InvoiceTotal() {
        return jLabel_InvoiceTotal;
    }

    public Action_Listener_Buttons getListenerBtns() {
        return listenerBtns;
    }
    
  
     

}
